const authActionTypes = {
    LOG_IN_START: "LOG_IN_START",
    LOG_IN_SUCCESS: "LOG_IN_SUCCESS",
    LOG_IN_FAILURE: "LOG_IN_FAILURE",
    LOG_OUT: "LOG_OUT",
    REGISTER_START: "REGISTER_START",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
    UPDATE_REGISTER_PROFILE: "UPDATE_REGISTER_PROFILE",
    ADD_REGISTER_SUGGESTION: "ADD_REGISTER_SUGGESTION",
    REMOVE_REGISTER_SUGGESTION: "REMOVE_REGISTER_SUGGESTION"
}

export default authActionTypes